name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_IMAGE }}/techstore:latest .

    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWRD }} | docker login -u ${{ secrets.DOCKER_IMAGE }} --password-stdin  

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_IMAGE }}/techstore:latest

    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_IMAGE }}/techstore:latest
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:80 --name app ${{ secrets.DOCKER_IMAGE }}/techstore:latest