name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_IMAGE }}/techstore:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_IMAGE }}/techstore:latest

    - name: Copy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        source: "techstore.tar"
        target: "/home/ubuntu/"

    - name: Deploy on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker load < techstore.tar
          docker stop app || true
          docker rm app || true
          docker run -d -p 80:80 --name app techstore